# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 8

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'horizontal'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 2
inner.vertical = 2
outer.left = 2
outer.bottom = 2
outer.top = 2
outer.right = 2

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
#                   sectionSign (ISO keyboards only, european keyboards only)
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut
# (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# Mode entry bindings (keep main slim)
ctrl-space = [
  'mode nav',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight show',
]
alt-r = 'mode resize'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

[mode.nav.binding]
# Focus with h/j/k/l; hold shift to move
h = 'focus left'
j = 'focus down'
k = 'focus up'
l = 'focus right'
shift-h = 'move left'
shift-j = 'move down'
shift-k = 'move up'
shift-l = 'move right'

ctrl-h = 'join-with left'
ctrl-j = 'join-with down'
ctrl-k = 'join-with up'
ctrl-l = 'join-with right'

# Resize with minus/equal
minus = 'resize smart -50'
equal = 'resize smart +50'

shift-leftSquareBracket = ['move left', 'move left']
shift-rightSquareBracket = ['move right', 'move right']

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
slash = 'layout tiles horizontal vertical'
shift-semicolon = 'layout tiles horizontal vertical'
shift-space = 'layout tiles horizontal vertical'
shift-e = 'layout tiles horizontal vertical'
comma = 'layout accordion horizontal vertical'
semicolon = 'layout accordion horizontal vertical'
space = 'layout accordion horizontal vertical'
e = 'layout accordion horizontal vertical'

m = ['fullscreen']

o = ['focus-back-and-forth']
r = [
  'flatten-workspace-tree',
  'layout accordion horizontal',
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
] # reset layout (like vim's :r)
# f = [
#   'layout floating tiling',
#   'mode main',
# ] # Toggle between floating and tiling layout (like vim's :f)

v = [
  'layout accordion horizontal',
  'move down',
  'move-mouse window-lazy-center',
  'layout tiles horizontal',
  'move-mouse window-lazy-center',
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
]
shift-v = [
  'layout accordion horizontal',
  'move down',
  'move-mouse window-lazy-center',
  'layout tiles horizontal',
  'move-mouse window-lazy-center',
  'move left',
  'move left',
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
]
s = [
  'layout accordion vertical',
  'move right',
  'layout tiles vertical',
  'move-mouse window-force-center',
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
]

p = ['workspace --wrap-around prev', 'move-mouse window-force-center']
n = ['workspace --wrap-around next', 'move-mouse window-force-center']
shift-p = ['move-node-to-workspace --wrap-around --focus-follows-window prev']
shift-n = ['move-node-to-workspace --wrap-around --focus-follows-window next']

# Workspace controls
tab = 'workspace-back-and-forth'
shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Return to main
esc = [
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
]
enter = [
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
]

[mode.service.binding]
# Vim-like service mode bindings
r = [
  'flatten-workspace-tree',
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
] # reset layout (like vim's :r)
f = [
  'layout floating tiling',
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
] # Toggle between floating and tiling layout (like vim's :f)
backspace = [
  'close-all-windows-but-current',
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
] # close all but current

# Vim-like join operations
shift-h = [
  'join-with left',
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
]
shift-j = [
  'join-with down',
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
]
shift-k = [
  'join-with up',
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
]
shift-l = [
  'join-with right',
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
]

# Additional vim-like shortcuts
# Escape to return to main mode
esc = [
  'mode main',
  'exec-and-forget ~/.dotfiles/aerospace/border-highlight hide',
]
