#!/usr/bin/env zsh

set -euo pipefail

ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM_PLUGINS="$ZSH/custom/plugins"
ZSH_COMPLETIONS="$HOME/.zfunc"

[[ ! -d $ZSH ]] && RUNZSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc

plugins=(
	https://github.com/Aloxaf/fzf-tab
	https://github.com/zsh-users/zsh-autosuggestions
	https://github.com/zsh-users/zsh-syntax-highlighting
	https://github.com/junegunn/fzf-git.sh
	https://github.com/zsh-users/zsh-completions
)
for plugin in "${plugins[@]}"; do
	echo "Installing $plugin"
	directory="$ZSH_CUSTOM_PLUGINS/$(basename "$plugin" .git)"
	if [ -d "$directory" ]; then
		(cd "$directory" && git pull)
	else
		git clone "$plugin" "$directory"
	fi
done

function generate_completions() {
	mkdir -p "$ZSH_COMPLETIONS"

	uv generate-shell-completion zsh >"$ZSH_COMPLETIONS/_uv"
	uvx --generate-shell-completion zsh >"$ZSH_COMPLETIONS/_uvx"
	uvx ruff generate-shell-completion zsh >"$ZSH_COMPLETIONS/_ruff"
	sesh completion zsh >"$ZSH_COMPLETIONS/_sesh"

	autoload -Uz compinit && compinit
}

generate_completions
zsh
