#!/usr/bin/env zsh

set -euo pipefail

ZSH_COMPLETIONS="$HOME/.zfunc"

function generate_completions() {
	mkdir -p "$ZSH_COMPLETIONS"

	uv generate-shell-completion zsh >"$ZSH_COMPLETIONS/_uv"
	uvx --generate-shell-completion zsh >"$ZSH_COMPLETIONS/_uvx"
	uvx ruff generate-shell-completion zsh >"$ZSH_COMPLETIONS/_ruff"
	sesh completion zsh >"$ZSH_COMPLETIONS/_sesh"

	autoload -Uz compinit && compinit
}

generate_completions
zsh
